version: '3.1'
services:  
 
    db:
        image: mdillon/postgis
        hostname: db
        volumes:
          - ./postgres_data:/var/lib/postgresql
            
        # uncomment this to expose port 5432 to the host
        # WARNING: THIS IS UNSAFE USE ONLY FOR DEV
        #ports:
         # - "5432:5432"
        environment:
            POSTGRES_USER: admin 
            POSTGRES_PASSWORD: 1515 
            POSTGRES_DB: taxi2 
            
    adminer: 
        image: adminer 
        restart: always 
        ports: 
          - 8081:8080 
    taxi: 
        environment: 
            #- ASPNETCORE_ENVIRONMENT=Docker
            - AWS_SECRET_ACCESS_KEY=7HJEgQZ52YoiSm/ZtRz+0zg0YrvCvkGs4vm82jCH 
            - AWS_ACCESS_KEY_ID=AKIAIIX23JKI7LNELINQ 
            - JWT_KEY=hjhkjbhjghgfhjgjhgjhghjguyd
            - GOOGLE_API_KEY=AIzaSyAcwM7Cr6DuIaqp3dbf3rg-88kNPIQiO94
            - TAXI_DB_CONN=Server=db;Port=5432;Database=taxi2;User Id=admin;Password=1515;
        depends_on: 
            - db
        image: vosmushko/taxi:post50
        build:
            context: .
            dockerfile: Dockerfile
        restart: always 
        ports: 
          - "8080:80"
        #command: "-c 'while !</dev/tcp/db/5432;echo 12312; do sleep 1;done;'"
